### PR TITLE
REPOSITORIES.md file

### PR DESCRIPTION
**Pull request by jvanz**
## Description

 Adds the REPOSITORIES.md file. This document provides definitions of the scopes and statuses of Kubewarden repositories.

Fix https://github.com/kubewarden/kubewarden-controller/issues/684

### CODE REVIEW

**Review by viccuad — APPROVED** [review]
LGTM!

**Comment by viccuad** [comment]
I don't think this fixes https://github.com/kubewarden/kubewarden-controller/issues/684, while it explains the repository groups, we are still missing a list table of them as in https://github.com/falcosecurity/evolution/blob/main/README.md#repositories.

**Comment by jvanz** [comment]
> I don't think this fixes [kubewarden/kubewarden-controller#684](https://github.com/kubewarden/kubewarden-controller/issues/684), while it explains the repository groups, we are still missing a list table of them as in https://github.com/falcosecurity/evolution/blob/main/README.md#repositories. I think we could start by putting everything into `kubewarden/community`, without separating things into yet another repo as falco does with `falcosecurity/evolution`.

I'm aware that the table is missing. However, as we are following the falco example, I decided to keep the table for later when  we add the README file. I haven't done this here because I'm writing the README file and noticed that we miss other documentation that I would like add later to keep the PR small enough to be quickly reviewed.

**Review by flavio — APPROVED** [review]
LGTM

**Pull request merged**
